version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        networks:
            - laravel-net

    nginx:
        image: nginx:latest
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public
        depends_on:
            - app
        networks:
            - laravel-net

    db:
        image: postgres:latest
        container_name: laravel-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - laravel-net

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        networks:
            - laravel-net

networks:
    laravel-net:

volumes:
    dbdata:
